### ISSUE TITLE
Unable to remove shortcuts

### ISSUE THREAD

**Issue by ImAnnoying** [stanipintjuk/Silverfish#1]
When I try to slide shortcuts down to the remove bar they don't do anything. Sometimes they'll even launch themselves.

**Comment by stanipintjuk** [comment]
What phone do you have? Some phones allow the user to drag all the way to the ouside of the screen, in that case the drag event is considered to be cancelled and a drop event is not triggered and so the removal of the shortcut is not triggered. 

I will have to do some RTFM:ing in order to fix this issue.

As a workaround for now: do not drag the shortcut _all_ the way down to the border but just enough to be able to drop it on the "remove" text.

**Comment by ImAnnoying** [comment]
Anytime I try to drop it near the remove bar nothing happens, no matter how far or near... Sometimes they even start themselves if I hold them for too long. I have a Galaxy SIII Neo running CM 12.1

**Comment by stanipintjuk** [comment]
I just pushed a commit that manages the corner drop in a different way and so I think that this issue is also solved. Though you would have to clone and build the app yourself to test it because the changes are not on f-droid at the moment
