### ISSUE TITLE
Make status bar transparent (enhancement)

### ISSUE THREAD

**Issue by Lonami** [stanipintjuk/Silverfish#24]
I'm not aware of which Android version support this, but for those with support, the status bar not being transparent makes it look a bit odd:
![Non-transparent status bar](https://cloud.githubusercontent.com/assets/6297805/17928980/be34aad6-69fd-11e6-8c90-ca724b403d2e.jpg)

Edit: Actually, perhaps it was even a better idea to hide the entire status bar. Perhaps as a setting?
Edit 2 (I rush when submitting issues): KitKat and above support this (see [here](http://blog.raffaeu.com/archive/2015/04/11/android-and-the-transparent-status-bar.aspx) for a how-to)
Edit 3: [More](http://stackoverflow.com/a/20573595/4759433) and [more](http://stackoverflow.com/a/8273225/4759433) (how to hide it). Worth looking, really!

**Comment by stanipintjuk** [comment]
I am working on it.  In the mean time I will fix some more UI stuff

**Comment by neckcen** [comment]
While we're on the topic of UI, I'd prefer if the black background behind the widget was an option. Most widgets already come with a background or are designed to work without one.

**Comment by yllwboy** [comment]
If you decide to hide the status bar, please have that as an optional thing, I still might want to see battery percentage, time and notifications without having to swipe my finger to make the status bar show up every time.

Also, please consider the above as well, neckcen's idea is good.

**Comment by stanipintjuk** [comment]
I agree. Completely hiding the status bar is stupid.

The dark background should be easy enough to add as an option.

I am planning to write a setting activity soon, and these are the options I have thought of so far:

<b>UI</b>
- Show/hide statusbar
- Show/hide icon labels in home screen / app drawer
- Change background color of app drawer and widget
- Enable / disable background for widget
- Change widget (while this is already possible to do by long clicking the widget on home screen I still think it is a good idea to have another way to be able to change the widget)

Please come with more UI option suggestions if you can think of any

**Comment by neckcen** [comment]
Another UI idea:
- Completely disable direct modification of the home screen. My use case: non tech-savy people accidentally removing apps by long press and then panicking.

**Comment by Lonami** [comment]
1. What do you mean by "direct modification"? How else would we modify it?
2. Apps are not simply removed from the _Home screen_ by long tapping. You must drag them to the bottom, where it says "Remove".
3. Even if they're non techy, it is not hard to explain them that they can swipe their finger to the right to show all the applications.

**Comment by neckcen** [comment]
1. From the settings (through the widget change option for example) or by turning off the lock (which would be a toggle: dis/allow direct modification of the home screen).
2. It was just a random example from my past experience with other launchers, probably not the best one sorry. To be fair there isn't that much that could happen by accident with Silverfish's current home screen, I'm mostly suggesting this for the future (if apps can be moved, grouped, icons changed, ...).
3. Gives me another UI option idea: PIN lock for the drawer.

Also, I think I wasn't specific enough. When I say non tech-savy I do not mean slightly confused by technology. I mean people with poor dexterity (hard to target specific area, tend to long press by accident, swipe instead of tap twice, ...), sometime poor eyesight and absolutely no clue how it works. Imagine: 90yo grandparents using their phone to see their grandkids latest pictures or infants messing around with a fun game.

With that said, these people might be out of the scope of Silverfish or even android altogether. But I think some extra settings go a long way to make the launcher usable for them so I brought it up. I would understand these options not being integrated in the end though.

**Comment by Lonami** [comment]
Every suggestion is appreciated, and after some talk yes, being able to lock the home screen is a good idea, as well as password protecting some applications (perhaps for a very future), but all these would be better as a new issue in my opinion. One can't expect to come into "Make status bar transparent" and remember that we really had to "Add a PIN lock to the drawer"!

**Comment by neckcen** [comment]
A valid point, if @stanipintjuk also agree I can create the relevant issues.

**Comment by Lonami** [comment]
You don't need @stanipintjuk approval to post new issues, simply do it! That's what they're for :)

**Comment by stanipintjuk** [comment]
@neckcen yes please, make a new issue :)

**Comment by Lonami** [comment]
> I'd prefer if the black background behind the widget was an option.

@neckcen please open up a new issue if you still want this feature. The title of this issue is not relevant and it's hard to find what people want to be done on the launcher.

Closing the issue since the status bar has been transparent for a while now.
