### ISSUE TITLE
Disable app uninstall when dragging apps above tabs

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [stanipintjuk/Silverfish#36]
When moving apps to different tabs, dragging an app to the bottom tab can be tricky since the uninstall action shows up with a red highlight and covers part of the bottom of the bottom tab. Disabling the uninstall function when dragging an app above tabs would make working with the bottom tab much easier. Alternatively, moving the drag-to-delete area to a place that's out of the way could work too.

**Comment by Lonami** [comment]
I think it's a good idea, either don't invoke the uninstall intent if dragging on a tab or...:
![aa](https://cloud.githubusercontent.com/assets/6297805/18551668/b1d0d3ce-7b59-11e6-8474-4aa58b7872d6.png)

**Comment by DerVerruckteFuchs** [comment]
The corner does seem like a good place. It should be easy enough to uninstall apps one-handed that way. If there was ever an option to line up all apps on the bottom for large screens, the uninstall corner area would need the be moved to the top of course.

**Comment by Lonami** [comment]
The uninstall corner area could move, but it doesn't have to (in my opinion) even if there were apps below it. If you don't want to uninstall, after the uninstall area pops up, drop the app outside the area and it won't get uninstalled. It will be sorted and placed in the same location as it was before. I would find it annoying to have to move my finger up so high!

Also, having an area which you don't know where it will appear (you _do_, but it's not something you think about) seems a bit annoying.

**Comment by DerVerruckteFuchs** [comment]
For big phones, having the uninstall area jump to the top would be a problem. Your idea would seem to work better there, and for most phones really. It would be a little weird to have it under apps, since I'm used to seeing the uninstall area by itself. The automatic alphabetical sorting when dropping apps prevents it from being an issue though.

**Comment by stanipintjuk** [comment]
I really like your idea Lonami. It is not perfect but it is much better than how it is done right now

**Comment by quaap** [comment]
FYI: as a test and learning exercise I implemented a version of this.  After testing I found the bottom center worked better because on the right edge you could accidentally trigger a return to the homescreen.  The dropzone might need to be made bigger, but it works.

![silverfish-uninstall](https://cloud.githubusercontent.com/assets/20132877/20270570/305178bc-aa4d-11e6-9dbf-fb10309978cd.png)
![silverfish-remove](https://cloud.githubusercontent.com/assets/20132877/20270571/30526ace-aa4d-11e6-8568-c35ebf7b8a8e.png)

You can find it in my fork/branch: https://github.com/quaap/Silverfish/tree/drag-drop-center-delete 
If you'd like I could start a pull request.

**Comment by Lonami** [comment]
I like it @quaap, good job! However, there are two little caveats:
1. For me it looks like a [rectangle](https://cloud.githubusercontent.com/assets/6297805/20276360/31e96726-aa9c-11e6-8cbd-38ae88e6cc95.jpg)! No gradient, no round shape.
2. Maybe a trash-like icon would look better?

**Comment by quaap** [comment]
Weird. I could have forgotten to commit something, or maybe it's an API version difference. I'll check it out again later today. Thanks for testing!

**Comment by quaap** [comment]
I think the problem _may_ have been that I specified the gradientRadius as "100" instead of "100%" in red_gradient.xml.  But I'm not sure: the docs are confusing on that point. I've just tested in a low-resolution emulator and it works as expected.  When I leave off the "%" is becomes more of a solid rectangle with only a little gradient showing.  Pull the latest change and give it a try!

**Comment by Lonami** [comment]
> I think the problem may have been that I specified the gradientRadius as "100" instead of "100%" [...]

[Nope](https://gist.github.com/XyLoNaMiyX/e586a63716f9df3e852cdaf8d41d1a26). Without the `%` it does _not_ crash, but it renders a rectangle.

In the android layout preview, with the `%` it doesn't work; without the `%` it does render half circle. Awkward.

**Comment by quaap** [comment]
Strange.  I don't receive a crash with the %, and the docs say it's legal.  Not sure what's going on here.  For whatever reason,  your device is reporting the width as zero, and mine isn't.  I'll mess around with it again later when my baby naps.  Thanks for checking it out.

**Comment by stanipintjuk** [comment]
Very strange. I can confirm that the red circle looks good on both my Nexus 5X with Android 7 and my Samsung Galaxy Mini with Cyanogenmod 13.0

What phone do you have @XyLoNaMiyX ?

**Comment by Lonami** [comment]
Sony Xperia M4 Aqua with [this ROM](http://forum.xda-developers.com/m4-aqua/development/5-0-aosgp-based-stock-t3262330), based on AOSP 5.0.

**Comment by Lonami** [comment]
Alright, I got it working. It's not `"100%"` but rather... `"100%p"`. Yes, [ridiculous](http://stackoverflow.com/a/26989027).

Edit: I created a [PR](https://github.com/quaap/Silverfish/pull/1) on your fork, @quaap.
